name: publish

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner != '' && github.repository_owner || 'default' | lower }}/hello-docker-gcr-demo:latest
          docker run ghcr.io/${{ github.repository_owner != '' && github.repository_owner || 'default' | lower }}/hello-docker-gcr-demo:latest
          docker push ghcr.io/${{ github.repository_owner != '' && github.repository_owner || 'default' | lower }}/hello-docker-gcr-demo:latest