name: publish

on: [push]

jobs:
  publish-java17-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build ./java/17 --tag ghcr.io/ishotft/java_17custom:latest
          docker push ghcr.io/ishotft/java_17custom:latest